### ISSUE TITLE
Codice fiscale

### ISSUE THREAD

**Issue by eleftrik** [nigrosimone/codice-fiscale#6]
Il codice fiscale `LMRBHM74A01Z3P0U` non viene riconosciuto come valido.
https://telematici.agenziaentrate.gov.it/VerificaCF/Scegli.do?parameter=verificaCf lo riconosce come valido.

Grazie

**Comment by eleftrik** [comment]
Se può essere utile, https://github.com/DavidePastore/codice-fiscale lo valida correttamente

**Comment by nigrosimone** [comment]
Ciao @eleftrik ho provato **LMRBHM74A01Z3P0U** con la mia libreria e risulta valido. Ho anche aggiunto **LMRBHM74A01Z3P0U** al set dei test automatici https://github.com/nigrosimone/codice-fiscale/commit/ac94fc3357d04151077d8a784f4949764cfbe45b e passa tutti i test. 

se provo:

```php
<?php
require "vendor/autoload.php";
use NigroSimone\CodiceFiscale;

$cf = new CodiceFiscale();

if ($cf->validaCodiceFiscale('LMRBHM74A01Z3P0U')) {
    echo 'Codice fiscale corretto';
    printf("<p>Giorno: %s</p>", $cf->GetGiornoNascita());
    printf("<p>Mese: %s</p>", $cf->GetMeseNascita());
    printf("<p>Anno: %s</p>", $cf->GetAnnoNascita());
    printf("<p>Comune: %s</p>", $cf->GetComuneNascita());
    printf("<p>Sesso: %s</p>", $cf->GetSesso());
} else {
    echo 'Codice fiscale NON corretto';
}
```

ottengo:

```
Codice fiscale corretto
Giorno: 01
Mese: 01
Anno: 74
Comune: Z330
Sesso: M
```

Forse stai usando una vecchia versione di questa libreria? qui c'è il codice dell'ultima versione https://github.com/nigrosimone/codice-fiscale/blob/master/src/CodiceFiscale.php
Considera che circa un mese fa è stata aggiornata risolvendo un problema proprio sulla validazione di alcuni codici fiscale

Fammi sapere

**Comment by eleftrik** [comment]
Ciao @nigrosimone, perdona la segnalazione errata e anche il ritardo nel riscontro. Colpa mia: in questo caso, utilizzo il tuo codice in una vecchia web app ad uso interno (stack obsoleto, niente Composer, ecc. - no comment :-P ) e stupidamente non mi ero accorto che non stavo usando la versione più aggiornata.
Con la versione relativa all'ultimo commit confermo che funziona tutto correttamente.
Grazie ancora.

**Comment by nigrosimone** [comment]
Ottimo! Grazie per il feedback
